--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
http_port: 8098
pb_port: 8087
handoff_port: 8099
host: 127.0.0.1
source: /Users/jorgemoscat/Dev/riak-1.2.1/rel/riak/bin
min_port: 9009
root: !ruby/object:Pathname
  path: /Users/jorgemoscat/Dev/thanxup-api/db/development/4
cookie: '75734_547003'
env: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  riak_core: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    ring_creation_size: 64
    ring_state_dir: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/ring
    slide_private_dir: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/data/slide-data
    platform_bin_dir: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/bin
    platform_etc_dir: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/etc
    platform_log_dir: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/log
    platform_data_dir: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/data
    http:
    - - 127.0.0.1
      - 9009
    handoff_port: 9011
  riak_kv: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    storage_backend: :riak_kv_bitcask_backend
    map_js_vm_count: 8
    reduce_js_vm_count: 6
    hook_js_vm_count: 2
    mapper_batch_size: 5
    js_max_vm_mem: 8
    js_thread_stack: 16
    riak_kv_stat: true
    legacy_stats: true
    vnode_vclocks: true
    http_url_encoding: :on
    legacy_keylisting: false
    mapred_system: :pipe
    mapred_2i_pipe: true
    listkeys_backpressure: true
    add_paths: []
    pb_ip: 127.0.0.1
    pb_port: 9010
  riak_search: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    enabled: true
  luwak: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    enabled: true
  merge_index: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    buffer_rollover_size: 1048576
    max_compact_segments: 20
    data_root: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/data/merge_index
  eleveldb: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    data_root: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/data/leveldb
  bitcask: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    data_root: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/data/bitcask
  lager: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    crash_log_size: 10485760
    crash_log_msg_size: 65536
    crash_log_date: $D0
    crash_log_count: 5
    error_logger_redirect: true
    handlers: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      lager_console_backend: :info
      lager_file_backend:
      - - /Users/jorgemoscat/Dev/thanxup-api/db/development/4/log/error.log
        - :error
      - - /Users/jorgemoscat/Dev/thanxup-api/db/development/4/log/console.log
        - :info
    crash_log: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/log/crash.log
  riak_sysmon: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    process_limit: 30
    port_limit: 30
    gc_ms_limit: 100
    heap_word_limit: 40111000
    busy_port: true
    busy_dist_port: true
  sasl: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    sasl_error_logger: false
  riak_control: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    enabled: false
    auth: :userlist
    userlist: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      user: pass
    admin: true
vm: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  +K: true
  +A: 64
  -smp: enable
  +W: w
  -env ERL_MAX_PORTS: 4096
  -env ERL_FULLSWEEP_AFTER: 0
  -env ERL_CRASH_DUMP: /Users/jorgemoscat/Dev/thanxup-api/db/development/4/log/erl_crash.dump
  -name: riak738625@127.0.0.1
  -setcookie: '75734_547003'
